name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libglm-dev libglfw3-dev libxxf86vm-dev libxi-dev vulkan-tools libvulkan-dev  vulkan-utility-libraries-dev spirv-tools libfontconfig1-dev glslc libfl-dev libglew-dev ccache llvm
        version: 1.0
        execute_install_scripts: true

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true

    - name: make release
      run: make clean && make -j4 CXX="ccache clang++" release

    - name: make debug
      run: make clean && make -j4 CXX="ccache clang++" debug

    - name: run tests  
      run: make clean && make -j4 CXX="ccache clang++" test

    - name: ccache stats
      run: ccache -s

